# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 650)
        Form.setStyleSheet("#Form\n"
"\n"
"{\n"

"background-color: qlineargradient(spread:repeat, x1:0.517, y1:0, x2:0.522, y2:1, stop:0 rgba(172, 172, 172, 223), stop:1 rgba(72, 72, 72, 245));\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: white;\n"
"    font: bold 15px;\n"
"    border: 1px solid rgb(148, 148, 148) ;\n"
"    border-radius: 10px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(95, 95, 95);\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #F0F0F0;\n"
"    border: 2px solid rgb(200, 200, 200) ;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font: 12px \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(111, 111, 111);\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"\n"
"#button{\n"
"background-color: qlineargradient(spread:repeat, x1:0.517, y1:0, x2:0.522, y2:1, stop:0 rgba(172, 172, 172, 223), stop:1 rgba(72, 72, 72, 245));\n"
"}\n"
"#Title\n"
"{\n"
"color: rgb(240, 240, 241);\n"
"font: 22pt \"Gabriola\";\n"
";\n"
"}\n"
"\n"
"#label\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
";\n"
"}\n"
"#label_5\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
"\n"
"}\n"
"#label_2\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
"\n"
"}\n"
"#label_3\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
"}\n"
"#label_4\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
"}\n"
"#label_6\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"Gabriola\";\n"
"}\n"
"#sonuc\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Gabriola\";\n"
"}\n"
"#predict\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"    font: 15pt \"MV Boli\";\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 650))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("home.jpg"))
        self.label.setObjectName("label")
        self.sonuc = QtWidgets.QLabel(Form)
        self.sonuc.setGeometry(QtCore.QRect(110, 500, 71, 31))
        self.sonuc.setObjectName("sonuc")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 400, 191, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.Title = QtWidgets.QLabel(Form)
        self.Title.setGeometry(QtCore.QRect(95, 80, 310, 61))
        self.Title.setObjectName("Title")
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(110, 317, 191, 48))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 220, 191, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.predict = QtWidgets.QLabel(Form)
        self.predict.setGeometry(QtCore.QRect(190, 500, 131, 31))
        self.predict.setObjectName("predict")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 460, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 360, 191, 48))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 270, 191, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sonuc.setText(_translate("Form", "Sonuç"))
        self.label_5.setText(_translate("Form", "Özellik 5"))
        self.Title.setText(_translate("Form", "House Price Prediction App"))
        self.label_3.setText(_translate("Form", "Özellik 3"))
        self.label_2.setText(_translate("Form", "Özellik 1 "))
        self.predict.setText(_translate("Form", ""))
        self.pushButton.setText(_translate("Form", "predict"))
        self.label_4.setText(_translate("Form", "Özellik 4"))
        self.label_6.setText(_translate("Form", "Özellik 2"))
